//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 11:35:11 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:epcglobal:epcis:xsd:1")
package com.oliot.eca.model.epcis;
